#ifndef _WEAPONLIST_H_
#define _WEAPONLIST_H_
//===================================================================================
#define WEAPONLIST_BAT 2
#define WEAPONLIST_ENGINEERPISTOL 40
#define WEAPONLIST_SCATTERGUN 17
#define WEAPONLIST_ROCKETLAUNCHER 23
#define WEAPONLIST_SHOVEL 10
#define WEAPONLIST_FLAMETHROWER 26
#define WEAPONLIST_AXE 4
#define WEAPONLIST_PIPEBOMBLAUNCHER 24
#define WEAPONLIST_STICKYBOMBLAUNCHER 25
#define WEAPONLIST_BOTTLE 3
#define WEAPONLIST_MINIGUN 19
#define WEAPONLIST_SANDVICH 58
#define WEAPONLIST_FISTS 9
#define WEAPONLIST_WRENCH 11
#define WEAPONLIST_BUILDER 45
#define WEAPONLIST_DESTRUCTOR 46
#define WEAPONLIST_NEEDLEGUN 21
#define WEAPONLIST_BLUTSLAUGER 21
#define WEAPONLIST_MEDIGUN 49
#define WEAPONLIST_BONESAW 12
#define WEAPONLIST_RIFLE 18
#define WEAPONLIST_SMG 20
#define WEAPONLIST_KUKRI 5
#define WEAPONLIST_REVOLVER 24
#define WEAPONLIST_SAPPER 48
#define WEAPONLIST_KNIFE 8
#define WEAPONLIST_DISGUISE 47
#define WEAPONLIST_FLAREGUN 57
#define WEAPONLIST_ENERGYDRINK 58
#define WEAPONLIST_SPYPISTOL 42
#define WEAPONLIST_HEAVYSHOTGUN 15
#define WEAPONLIST_PYROSHOTGUN 16
#define WEAPONLIST_SOLDIERSHOTGUN 14
#define WEAPONLIST_SCOUTPISTOL 41
#define WEAPONLIST_ENGINEERSHOTGUN 13
//===================================================================================
#endif